import{S as L,i as c,a as m}from"./assets/vendor-89feecc5.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const y of s.addedNodes)y.tagName==="LINK"&&y.rel==="modulepreload"&&l(y)}).observe(document,{childList:!0,subtree:!0});function t(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerpolicy&&(s.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?s.credentials="include":e.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(e){if(e.ep)return;e.ep=!0;const s=t(e);fetch(e.href,s)}})();const g=document.querySelector(".form");document.querySelector("input");document.querySelector(".gallery-box");const d=document.querySelector(".gallery"),i=document.querySelector(".loader"),p=document.querySelector(".loader-bottom"),n=document.querySelector(".loading-btn");let a=1,u="",f=40;const h=new L(".gallery a",{nav:!0,captionDelay:250,captionsData:"alt",close:!0,enableKeyboard:!0,docClose:!0});g.addEventListener("submit",S);n.addEventListener("click",q);async function S(r){if(r.preventDefault(),a=1,i.style.display="none",u=r.target.elements.search.value.trim(),!u)return d.innerHTML="",n.style.display="none",c.info({position:"topRight",message:"Error enter any symbols"});try{i.style.display="block";const{data:{hits:o,total:t}}=await b(u,a);o.length>0?(i.style.display="none",d.innerHTML=v(o),h.refresh(),c.success({position:"topRight",message:`We found ${t} photos`}),n.style.display="block"):(d.innerHTML="",c.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})),t<=f&&(n.style.display="none")}catch{console.log("Error")}finally{i.style.display="none",g.reset()}}function b(r,o){return m.defaults.baseURL="https://pixabay.com/api/",m.get("",{params:{key:"41752354-d1ac8bee07efd7a3da621dba9",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:40}})}function v(r=[]){return r.reduce((o,t)=>o+`<li class="gallery-item">
        <a href=${t.largeImageURL}>
          <img class="gallery-img" src =${t.webformatURL} alt=${t.tags}/>
        </a>
        <div class="gallery-text-box">
          <p>Likes: <span class="text-value">${t.likes}</span></p>
          <p>views: <span class="text-value">${t.views}</span></p>
          <p>comments: <span class="text-value">${t.comments}</span></p>
          <p>downloads: <span class="text-value">${t.downloads}</span></p>
      </div>
      </li>`,"")}async function q(r){r.preventDefault(),p.style.display="block",n.style.display="none";try{a+=1;const{data:{hits:l,totalHits:e}}=await b(u,a),s=Math.ceil(e/f);if(a<s)p.style.display="none",n.style.display="block",d.insertAdjacentHTML("beforeend",v(l)),h.refresh();else return p.style.display="none",n.style.display="none",c.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})}catch(l){console.log(l)}const o=document.querySelector(".gallery-item:first-child"),t=o.getBoundingClientRect().height;console.log(t),console.log(o),window.scrollBy({top:2*t,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
