import{S as f,i,a as p}from"./assets/vendor-89feecc5.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&d(l)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function d(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const m=document.querySelector(".form");document.querySelector("input");document.querySelector(".gallery-box");const c=document.querySelector(".gallery"),a=document.querySelector(".loader");document.querySelector(".loader-bottom");const n=document.querySelector(".loading-btn");let y=1,u="",g=40;const b=new f(".gallery a",{nav:!0,captionDelay:250,captionsData:"alt",close:!0,enableKeyboard:!0,docClose:!0});m.addEventListener("submit",h);n.addEventListener("click",loadMore);async function h(s){if(s.preventDefault(),y=1,a.style.display="none",u=s.target.elements.search.value.trim(),!u)return c.innerHTML="",n.style.display="none",i.info({position:"topRight",message:"Error enter any symbols"});try{a.style.display="block";const{data:{hits:o,total:t}}=await L(u,y);o.length>0?(a.style.display="none",c.innerHTML=v(o),b.refresh(),i.success({position:"topRight",message:`We found ${t} photos`}),n.style.display="block"):(c.innerHTML="",i.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})),t<=g&&(n.style.display="none")}catch{console.log("Error")}finally{a.style.display="none",m.reset()}}function L(s,o){return p.defaults.baseURL="https://pixabay.com",p.get("/api/",{params:{key:"41752354-d1ac8bee07efd7a3da621dba9",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:40}})}function v(s=[]){return s.reduce((o,t)=>o+`<li class="gallery-item">
        <a href=${t.largeImageURL}>
          <img class="gallery-img" src =${t.webformatURL} alt=${t.tags}/>
        </a>
        <div class="gallery-text-box">
          <p>Likes: <span class="text-value">${t.likes}</span></p>
          <p>views: <span class="text-value">${t.views}</span></p>
          <p>comments: <span class="text-value">${t.comments}</span></p>
          <p>downloads: <span class="text-value">${t.downloads}</span></p>
      </div>
      </li>`,"")}
//# sourceMappingURL=commonHelpers.js.map
